/*
    WHEN A CUSTOMER SENDS A REQUEST 
    THIS FILE WILL SORT THROUGH ALL THE CONTRACTORS
    AND THEIR LOCATIONS. AND SORTS THEM BY HOW FAR AWAY
    THEY ARE FROM THE CUSTOMER. THEN REMOVES THE CONTRACTORS
    THAT ARE FURTHER THAN 50KM AWAY
*/